import os
os.system("pip install ez_setup")
os.system("pip install asyncio")
os.system("pip install aiohttp")
os.system("py -3 -m pip install -U discord.py")
os.system("pip install lyrics_extractor")
os.system("pip install git+https://github.com/pytube/pytube")
os.system("pip install ffmpeg")
os.system("pip install python-socketio[client]")
os.system("pip install semantic-version")
